train:
  _target_: src.datasets.OpportunityDataset
  root: "data/raw/opportunity"
  split: "train"
  window_length: 1000
  stride: 500
  target_hz: 100
  raw_hz: 30
  val_subject: 1
  test_subject: 2
  min_majority_ratio: 0.5
  normalize: true
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.OpportunityDataset
  root: "data/raw/opportunity"
  split: "val"
  window_length: 1000
  stride: 500
  target_hz: 100
  raw_hz: 30
  val_subject: 1
  test_subject: 2
  min_majority_ratio: 0.5
  normalize: true
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.OpportunityDataset
  root: "data/raw/opportunity"
  split: "test"
  window_length: 1000
  stride: 500
  target_hz: 100
  raw_hz: 30
  val_subject: 1
  test_subject: 2
  min_majority_ratio: 0.5
  normalize: true
  instance_transforms: ${transforms.instance_transforms.inference}
