train:
  _target_: src.datasets.PAMAP2Dataset
  root: "data/raw/pamap2"
  split: "train"
  protocol_mode: "yuan24_wrist10s"
  train_subjects: null
  val_subjects: null
  test_subjects: null
  use_optional: false
  window_length: 1000
  stride: 500
  feature_set: "wrist"
  imu_sensors: "acc16"
  include_hr: false
  min_majority_ratio: 0.0
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.PAMAP2Dataset
  root: "data/raw/pamap2"
  split: "val"
  protocol_mode: "yuan24_wrist10s"
  train_subjects: null
  val_subjects: null
  test_subjects: null
  use_optional: false
  window_length: 1000
  stride: 500
  feature_set: "wrist"
  imu_sensors: "acc16"
  include_hr: false
  min_majority_ratio: 0.0
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.PAMAP2Dataset
  root: "data/raw/pamap2"
  split: "test"
  protocol_mode: "yuan24_wrist10s"
  train_subjects: null
  val_subjects: null
  test_subjects: null
  use_optional: false
  window_length: 1000
  stride: 500
  feature_set: "wrist"
  imu_sensors: "acc16"
  include_hr: false
  min_majority_ratio: 0.0
  instance_transforms: ${transforms.instance_transforms.inference}
