train:
  _target_: src.datasets.SmokeForecastingDataset
  n_samples: 256
  context_length: 96
  horizon: 24
  n_channels: 1
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.SmokeForecastingDataset
  n_samples: 64
  context_length: 96
  horizon: 24
  n_channels: 1
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.SmokeForecastingDataset
  n_samples: 64
  context_length: 96
  horizon: 24
  n_channels: 1
  instance_transforms: ${transforms.instance_transforms.inference}
