train:
  inputs:
    _target_: src.transforms.Normalize1D
    mode: channel
    auto_fill_from_train: true
    eps: 1e-6
  targets:
    _target_: src.transforms.Normalize1D
    mode: channel
    auto_fill_from_train: true
    eps: 1e-6
inference:
  inputs:
    _target_: src.transforms.Normalize1D
    mode: channel
    auto_fill_from_train: true
    eps: 1e-6
  targets:
    _target_: src.transforms.Normalize1D
    mode: channel
    auto_fill_from_train: true
    eps: 1e-6
