train:
  inputs: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mode: channel
        auto_fill_from_train: true
inference:
  inputs: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.Normalize1D
        mode: channel
        auto_fill_from_train: true
