_target_: src.logger.CometMLWriter
project_name: "diploma-ts-model-distillation"
workspace: null
run_name: "diploma-ts-model-distillation"
mode: "online"
loss_names: ["loss", "task_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
